# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
#   namespace: producao
# spec:
#   type: ClusterIP
#   selector:
#     app: frontend
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
#     # nodePort: 30080
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: producao
spec:
  selector:
    app: frontend
  type: NodePort # ← troque
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
