# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
#   namespace: producao
# spec:
#   type: ClusterIP
#   selector:
#     app: frontend
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
